name: Branch Commit Notifier

on:
  push:
    branches:
      - '**'  # trigger on all branches

jobs:
  branch-commit-notifier-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current branch name
        run: |
          echo "A commit was pushed on branch: ${{ github.ref_name }}"
