name:"Branch commit notifer"

on: 
  push:
    branches:
      -'**' #trigger on all branches

jobs:
  branch-commit-notifier-job:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout code"
        uses: actions/checkout@v3

      - name: "print current branch name"
        runs: |
          echo "A commit was pushed on brach: ${{ github.ref_name}}"